services:
    _defaults:
        autoconfigure: false

    CoreShop\Component\Notification\Messenger\Handler\NotificationMessageHandler:
        arguments:
            - '@coreshop.repository.notification_rule'
            - '@coreshop.notification_rule.validation.processor'
            - '@CoreShop\Component\Notification\Processor\RuleApplierInterface'
            - '@Doctrine\Persistence\ConnectionRegistry'
        tags:
            - { name: messenger.message_handler, bus: coreshop.bus }

    CoreShop\Bundle\NotificationBundle\EventListener\MessengerListener:
        tags:
            - { name: kernel.event_subscriber }