CoreShop\Component\Notification\Model\NotificationRule:
  type: mappedSuperclass
  table: coreshop_notification_rule
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    name:
      column: name
      type: string
    type:
      column: type
      type: string
      nullable: true
    active:
      column: active
      type: boolean
    sort:
      column: sort
      type: integer
  manyToMany:
    conditions:
      targetEntity: CoreShop\Component\Rule\Model\ConditionInterface
      cascade:
        - all
      joinTable:
        name: coreshop_notification_rule_conditions
        joinColumns:
          notification_id:
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE
        inverseJoinColumns:
          action_id:
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE

    actions:
      targetEntity: CoreShop\Component\Rule\Model\ActionInterface
      cascade:
        - all
      joinTable:
        name: coreshop_notification_rule_action
        joinColumns:
          notification_id:
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE
        inverseJoinColumns:
          condition_id:
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE