framework:
    messenger:
        transports:
            coreshop_notification:
                dsn: "doctrine://default?queue_name=coreshop_notification"
                failure_transport: coreshop_notification_failed
                retry_strategy:
                    max_retries: 5
                    delay: 300000
                    multiplier: 2
            # we store failed messages here for admins to manually review them later
            coreshop_notification_failed:
                dsn: "doctrine://default?queue_name=coreshop_notification_failed"
                retry_strategy:
                    max_retries: 0

        routing:
            'CoreShop\Component\Notification\Messenger\NotificationMessage': coreshop_notification