CoreShop\Component\Notification\Model\NotificationRule:
  properties:
    type:
      - NotBlank: { groups: [coreshop] }
    active:
      - Type:
          type: integer
          groups: [coreshop]
    sort:
      - Type:
          type: integer
          groups: [coreshop]